version: '2'
services:
    codefest-app:
        image: codefest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://codefest-mysql:3306/codefest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codefest-mysql:
        extends:
            file: mysql.yml
            service: codefest-mysql
